name: Trigger auto deployment for myrobot-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/myrobot-container-app-AutoDeployTrigger-551cf6b2-d5f8-403f-8d5c-3b08eb49d49f.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: sitecheckrobot.azurecr.io
          username: ${{ secrets.MYROBOTCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.MYROBOTCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: sitecheckrobot.azurecr.io/myrobot-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MYROBOTCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n myrobot-container-app -g myrobot-rg-north-us --server sitecheckrobot.azurecr.io --username  ${{ secrets.MYROBOTCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.MYROBOTCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n myrobot-container-app -g myrobot-rg-north-us --image sitecheckrobot.azurecr.io/myrobot-container-app:${{ github.sha }}
